### ISSUE TITLE
Updating requirements

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group6#171]
## About

Since we got feedback about the system and specifically the templates in the community groups, we have to update our requirements.  

## Tasks

- [x] Add requirements regarding templates.
- [x] Add system requirements.

**Comment by gokceuludogan** [comment]
I have updated our requirements depending on what we talked, could you please review it? @OnurOrhan

**Comment by OnurOrhan** [comment]
I think it looks perfect, covering everything we talked about. @gokceuludogan
