### ISSUE TITLE
Creating Milestones and Issues for Front-End

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#177]
## About

Front-end team should decide on their roadmap and document their milestones and issues.

## Tasks

- [x] Create milestones(till the end of the project)
- [x] Open issues and assign related people + indicate deadlines

**Comment by gokceuludogan** [comment]
I think this issue is a bit general and not trackable :sweat_smile: I have no idea when the tasks will be marked as done. It could be better to either specialize this for the upcoming two/three weeks or close it :smile:
