### ISSUE TITLE
Android: Setting up Request Service and creating models

### ISSUE THREAD

**Issue by emreshome** [bounswe/bounswe2017group6#208]
## About
We decided to use [Retrofit](http://square.github.io/retrofit/)  package to get service from back-end. Also we have to
create models as in back-end in order to receive and send requests.

## Tasks

- [ ] Set up request service classes
- [ ] Create models

**Comment by barisucakturk** [comment]
Besides, we are planning to use volley package, am I right Emre?

**Comment by emreshome** [comment]
Retrofit package provides us all the functionality that we need, so I think there is no need to use volley. Also usage and implementation of retrofit is easier.
