### ISSUE TITLE
group-contents/:id endpoint bad response

### ISSUE THREAD

**Issue by ymanav** [bounswe/bounswe2017group6#294]
## About

Post method of this endpoint creates bad response. 

returns -
 {
"owner_id": 1, 
"content_type_id": 21, 
"components": [
{
   "component_type": "text",
   "order": 1, 
   "type_data": {"component_type":"text", 
   "order":1,
   "type_data":{"data": "asdf"}
}

}
]
}

expected - 

{
        "id": 46,
        "content_type": {
            "id": 21,
            "name": "Deneme1",
            "components": [
                "text"
            ],
            "component_names": [
                "text"
            ]
        },
        "created_date": "2017-11-17T22:07:38.649418+03:00",
        "modified_date": "2017-11-17T22:07:38.649448+03:00",
        "owner": {
            "url": "http://34.209.230.231:8000/users/1/",
            "id": 1,
            "username": "admin",
            "email": "admin@interesthub.com"
        },
        "owner_id": 1,
        "content_type_id": 21,
        "components": [
            {
                "id": 80,
                "component_type": "text",
                "order": 1,
                "type_data": {
                    "id": 45,
                    "data": "asdf"
                }
            }
        ]
    }

**Comment by yhkalayci** [comment]
This end point is changed.
