### ISSUE TITLE
Error creating group with a few tags 

### ISSUE THREAD

**Issue by gokceuludogan** [bounswe/bounswe2017group6#309]
## About

While trying to create groups with a list of tags, I am getting Internal Server Error. The request and the response are below.
 
## Visuals
* **Request**
![request](https://user-images.githubusercontent.com/9639399/32990835-7e7f56fe-cd41-11e7-8c8b-eb60c5648ce3.png)
* **Response**
![response](https://user-images.githubusercontent.com/9639399/32990834-7e600286-cd41-11e7-9f44-3a91665438dc.png)

**Comment by yhkalayci** [comment]
The problem is that given URL is not valid. However, it should return an error message warning about that problem.

**Comment by yhkalayci** [comment]
Now server responds with an error message with this type of validation errors.
