### ISSUE TITLE
Authorization at Login and Sign up with Google API 

### ISSUE THREAD

**Issue by barisucakturk** [bounswe/bounswe2017group6#311]
## About

-[ ] User should be signed up with Google or Facebook,
-[ ] User and his/her data (group,followers) should be kept properly when he/she is logged in.

**Comment by yhkalayci** [comment]
Do we really need this?

**Comment by barisucakturk** [comment]
At the first stage of project, we thought that we should implement this property in order to sign up easily. However, we should get attention on critical part of the project due to limited time. For now, we don't need this :)

**Comment by yhkalayci** [comment]
Then I am closing this issue until this feature is needed.
